### ISSUE TITLE
[Idea] Dynamic facade generation to overcome storage limitation

### ISSUE THREAD

**Issue by exoego** [ScalablyTyped/Distribution#19]
Currently, ScalablyTyped publishes its type facades to Bintray.
Unfortunately, Bintray free plan has 10GB storage limitation, which is small for ScalablyTyped's big ambition to provide type facade for all JS ecosystems !!
So cross-publishing for Scala versions and Scala.js versions is very unlikely, unless storage limitation is addressed, as mentioned in #7
(I could not found limitation about Sonatype OSS Repository Hosting. You may give it a try?)

My idea: ScalablyTyped become a sbt plugin to generate facades dynamically as `managed source` on demand.
If it is possible, you do not need to worry about storage limitation any more.
Something like this.
```scala
addSbtPlugin("org.scalablytyped" % "sbt-scalablytyped" % "xxxxxx")

val myAwesomeProject = project(".")
   .enablePlugin(ScalablyTypedPlugin)
   .settings(
      generatedTypeFacades := Seq(
        "d3" -> "5.5.0", // Generated on compile-time
      ),
      npmDependencies  in Compile := Seq(
        "d3" -> "5.5.0",
      )
   )
```

...Since I do not know much about managed source in sbt, this may be a stupid idea.

**Comment by mushtaq** [comment]
Event I do not understand this fully, but this question has bothered me too. Why is ScalablyTyped not generating facades dynamically? Thanks for bring this out.

**Comment by oyvindberg** [comment]
Hey there. Sorry, I didn't see notifications for this somehow.

Thanks for bringing this up, it is not a bad idea, and indeed a direction the project might take in the future. It is also an idea I have considered and decided not to pursue (for now). The reasons why I chose the direction of publishing are the following:

### Performance
People care about how long their build takes, and compiling ScalablyTyped is not fast. Compiling just the stdLib alone takes 60-200 seconds, and that's a prerequisite for almost all libraries. UI toolkits like material-ui takes 500 seconds, and the really big libraries (aws-sdk comes to mind) takes 40 min.
There is also the time taken to convert, and to download resources... My converter has not been written with performance in mind.

### Sharing code on top of typings
If all typings are locally generated source code, we have no way of sharing code to make them more usable. I'm talking about the facades in particular, but it could be any external library.

I think this part of ScalablyTyped is very important for success, and we would need to come up with something to replace it.

-----

For now I hope to find a solution to the storage problem (I have some ideas), and I'll be pretty happy with that. Once I get around to open sourcing the converter itself anyone can give this a shot.

**Comment by an-tex** [comment]
How much storage and transfer is (currently) roughly necessary?

**Comment by oyvindberg** [comment]
@an-tex one full build for one specific combination of scala and scala.js versions weighs a bit less than two gigabytes. We currently host around five releases of a given library before it's deleted

**Comment by oyvindberg** [comment]
sbt plugin is now in hush hush but open beta, and resolves this problem. See https://scalablytyped.org/docs/readme
