### ISSUE TITLE
Publish to release-repo

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Distribution#2]
For now we publish all artifacts continuously to `oyvindberg/ScalablyTyped` on bintray. All these artifacts can be considered snapshots, and should be labelled as such, while we should have a separate repo for releases so we don't clean them out.

Current plan:
- create `ScalablyTyped` bintray organization for releases
- keep my repo for snapshots

**Comment by mushtaq** [comment]
@oyvindberg Instead of publishing continuously to bintray, will it make sense to let people use the artifacts via [jitpack](https://jitpack.io)?

**Comment by oyvindberg** [comment]
Thats's a pretty cool idea! 
Do you have any experience with it? I wonder if it supports a monorepo like this, and if it can build dependencies transitively.

**Comment by mushtaq** [comment]
It works well for [our project](https://github.com/tmtsoftware/csw) which has many sbt modules. But there dependencies are specified using "dependsOn" unlike what ScalablyTyped does using "libraryDependencies". I have no experience with such mono-repos so need to think more.

BTW, jitpack allows customisations via [jitpack.yml](https://github.com/tmtsoftware/csw/blob/master/jitpack.yml), worth exploring further.

**Comment by Atry** [comment]
I don't think jitpack is able to build so many libraries in a single repository.

**Comment by oyvindberg** [comment]
Yeah, I would be surprised as well if that worked ootb. We could theoretically split up this repo into 6k GitHub repos, but I really wanted to avoid that since it's completely impossible to navigate here on GitHub. It would also add a lot of time to ci. It could be worth it, does anybody know how much storage we get with jitpack?

**Comment by Atry** [comment]
Technically, you can create 6K repositories with the help of [hub create](https://hub.github.com/hub-create.1.html) command-line tool and add them as submodules of the main repository.

**Comment by oyvindberg** [comment]
haha right yes. I'm sure that would be a world record in number of submodules for one project :)

As tempting as it sounds, this would make the whole CI process incredibly much more difficult/slow, which is super important because it has to scale all the way down to local development. Even one HTTP call performed 6000 times would add a lot of clock time. Adding 6000 pulls, commits and pushes would be *very* slow.

I'm very intrigued by jitpack, but I really want to avoid all those repos if possible

**Comment by Atry** [comment]
It's not slow on jitpack because jitpack is built on demand, that means if some of the submodules contain errors, the error will be first occur when someone tries to download the artifact from jitpack.

Unfortunately there is no report for a changeset that involves thousands of submodules unless explicitly triggering the builds.

**Comment by oyvindberg** [comment]
Yes, that part is fine. I already have a compile/build pipeline, so it would be natural to only publish new versions we know compile, and to do that transitively. We do that today in that failing versions of libraries are not pushed to bintray or to master.

The problem is actually that git/github/network is surprisingly slow:
```
oyvind-tso-public@ def time(thunk: => Unit): Long = {val t0 = System.currentTimeMillis; thunk; System.currentTimeMillis - t0} 
defined function time

oyvind-tso-public@ 0 to 6 map (_ => time(%git('pull))) sum 
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
res: Long = 10249L
```

That's more than a second for each pull, and a full CI build would need to pull/push all repos, meaning close to 14000 operations. We're easily talking 20k seconds just waiting. It's really hard to beat a monorepo for this stuff! and i say that somewhat begrudgingly :)

So anyways, not trying to be negative here - jitpack sounds like it would fit this project oh so well, given that most published artifacts will never see any use. I'll just need to think carefully how we could do it

**Comment by oyvindberg** [comment]
This ScalablyTyped distribution will never be stable and is superseded by sbt plugin which is now in hush hush but open beta. See https://scalablytyped.org/docs/readme
