### ISSUE TITLE
scala 2.13, Scala.js 1.0?

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Distribution#7]
There won't be cross builds of ScalablyTyped unless somebody donates the servers necessary. Only the initial versions will be for Scala 2.12, we'll upgrade as soon as possible.

**Comment by exoego** [comment]
Did you consider using CI (like Travis, CircleCI) to automate building and publishing?
Those have free plan for public repos.

**Comment by oyvindberg** [comment]
Building is mostly a solved problem, there is a private CI server which builds the entire thing nightly.  I don't think think Travis would be appropriate, it would take ages to build, and handling dependencies would be hard.

The main constraint is actually server space for publishing artifacts. A full build is 1.5 gigabytes or so, and we churn through ten gigs in a few months. Cross building would double/quadruple that.

**Comment by exoego** [comment]
Understood.
I found it, storage limitation of BinTray,  is also mentioned here.
https://github.com/oyvindberg/ScalablyTyped/blob/master/readme.md#is-it-production-ready

**Comment by mushtaq** [comment]
@oyvindberg  I really hope that 2.13 versions are available in near future. Most of our Scala projects are migrating to 2.13 now.

**Comment by oyvindberg** [comment]
It is coming @mushtaq . I've been focusing on improving the conversion rather than solving the storage problem, but I'm getting there. We're plenty forward compatible, my tests all run on scala 1.0.0-M8 and scala 2.13 :)

**Comment by mushtaq** [comment]
> my tests all run on scala 1.0.0-M8 and scala 2.13 :)

Wow! great to hear that. For my immediate need, I copied just 2 projects from this repo to [here](https://github.com/mushtaq/scalably-typed), so not blocked right now.

**Comment by nafg** [comment]
You could publish to a GCS or S3 bucket

**Comment by oyvindberg** [comment]
In the end I think this will take the form of an sbt plugin, so you have complete freedom yourself. It's currently in testing phase :)

**Comment by user753** [comment]
@oyvindberg Is it possible to use `ScalablyTypedConverter` as sbt task?
For example I would like to do something like
`sbt gen-typing react@16.12.0` to locally generate this directory `https://github.com/oyvindberg/ScalablyTyped/tree/master/r/react` code

**Comment by oyvindberg** [comment]
sbt plugin with free choice of versions is now in hush hush but open beta, and resolves this problem. See https://scalablytyped.org/docs/readme
