### ISSUE TITLE
Better React support

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Distribution#8]
People seem to want to combine props creation and component instantiation in one
Pretty easy to do, just need to spec it first.

Also if we do it, should we also generate code for popular scalajs react libraries? slinky and scalajs-react?

**Comment by an-tex** [comment]
I'd love both! I prefer scalajs-react so I'm having e.g. `Table(TableProps(dataSource = ...)).toScalaJSReact` all over the place ;) Would be awesome to have it down to `Table(dataSource = ...)`

**Comment by oyvindberg** [comment]
Yeah, no doubt it would be better. The solution space for this is rather large, so we'll work something out a bit later.

One thing that is clear is that *good* integration with scalajs-react is more work than good integration with slinky, since we'll need to rewrite all the callbacks and so on. I'll definitely appreciate some help with that down the road :)

**Comment by an-tex** [comment]
Sure I'd love to help! This library is awesome and saves me heaps of time :) 

A full solution incl Callbacks seems really a big task. Maybe it could be broken down to:

1. Construction  without Props 
2. Simple component facades for scalajs-react like in https://github.com/oyvindberg/ScalablyTypedDemos/blob/master/react-slick/src/main/scala/demo/Main.scala (hence not using callbacks just yet)
3. full fledged callbacky

**Comment by an-tex** [comment]
I like a few ideas of https://github.com/payalabs/scalajs-react-bridge . 
Especially:
- automatic conversion between collections e.g. `Seq` and `js.Array`
- that you can pass not only children, but also `TagMods` (e.g. for scalacss styling) to components
- eventhandlers using `Callback`s (it's just a `.runNow()`)

Would it be worth generating those `ReactBridgeComponent`s as a shortcut?

**Comment by oyvindberg** [comment]
We'll have an all new story and fantastic story on working with react components very soon :)

**Comment by an-tex** [comment]
brilliant, looking forward to it!

**Comment by oyvindberg** [comment]
sbt plugin with react flavours is now in hush hush but open beta, and resolves this problem. See https://scalablytyped.org/docs/readme
